name: Pull Request Validation

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Go Version from go.mod
        id: go_version
        run: echo "GO_VERSION=$(awk '/^go /{print $2}' go.mod)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check formatting
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not properly formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.2

      - name: Run Go Tests
        uses: actions/setup-go@v5
        run:
          make test
